### ISSUE TITLE
Improvement idea: structure repo to work as an external_components for ESPHome

### ISSUE THREAD

**Issue by spitfire** [assembly12/Foxess-T-series-ESPHome-Home-Assistant#21]
https://esphome.io/components/external_components.html#example-of-local-components

**Comment by SibrenVasse** [comment]
I've started working on this, you can check my progress on my fork: https://github.com/SibrenVasse/Foxess-T-series-ESPHome-Home-Assistant

**Comment by spitfire** [comment]
> I've started working on this, you can check my progress on my fork: https://github.com/SibrenVasse/Foxess-T-series-ESPHome-Home-Assistant



Hey, first of all thanks for working on that!
I've tried to migrate over by changing 

```
includes:
     - templates/Foxess-T-series-ESPHome-Home-Assistant/foxess_t_series.h
```

from this repo to

```
external_components:
  - source:
      type: git
      url: https://github.com/SibrenVasse/Foxess-T-series-ESPHome-Home-Assistant    
```

shown in your example yaml.


Unfortunately it spawned this error at compile time:

```
/config/foxess-inverter.yaml: In lambda function:
/config/foxess-inverter.yaml:122:32: error: expected type-specifier before 'foxesscomponent'
     auto foxesssensors = new foxesscomponent(id(uart_bus));
                                ^~~~~~~~~~~~~~~
/config/foxess-inverter.yaml:158:7: error: could not convert '{<expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>, <expression error>}' from '<brace-enclosed initializer list>' to 'std::vector<esphome::sensor::Sensor*>'
     };
       ^
```

which seem to be related to lambda function from https://github.com/assembly12/Foxess-T-series-ESPHome-Home-Assistant/blob/main/foxess-inverter.yaml (line 61-100 here).

Is there any way to cleanly replace that? I've seen your https://github.com/SibrenVasse/Foxess-T-series-ESPHome-Home-Assistant/blob/main/foxess-inverter.yaml.example, but I'm afraid it would completely replace my entity names and anything depending on them in the process.

**Comment by SibrenVasse** [comment]
You have to replace everything below the 'uart:' section with the sections from the new yaml example.

If you're worried about entities changing name in Home Asisstant, you have to make sure the new sensor has the same 'name' field in the yaml file. Like this:

```
button:
  - platform: restart
    name: "Foxess inverter restart"

text_sensor:
  - platform: template
    name: "T-Series Inverter Mode"
    id: "inverter_mode_text_sensor"
    icon: mdi:solar-power-variant

sensor:
  - platform: foxess_solar
    phase_a:
      voltage:
        name: "T-Series Grid Voltage R"
      current:
        name: "T-Series Grid Current R"
      active_power:
        name: "T-Series Grid Power R"
      frequency:
        name: "T-Series Grid Frequency R"
    phase_b:
      voltage:
        name: "T-Series Grid Voltage S"
      current:
        name: "T-Series Grid Current S"
      active_power:
        name: "T-Series Grid Power S"
      frequency:
        name: "T-Series Grid Frequency S"
    phase_c:
      voltage:
        name: "T-Series Grid Voltage T"
      current:
        name: "T-Series Grid Current T"
      active_power:
        name: "T-Series Grid Power T"
      frequency:
        name: "T-Series Grid Frequency T"

    pv1:
      voltage:
        name: "T-Series PV1 Voltage"
      current:
        name: "T-Series PV1 Current"
      active_power:
        name: "T-Series PV1 Power"
    pv2:
      voltage:
        name: "T-Series PV2 Voltage"
      current:
        name: "T-Series PV2 Current"
      active_power:
        name: "T-Series PV2 Power"
    pv3:
      voltage:
        name: "T-Series PV3 Voltage"
      current:
        name: "T-Series PV3 Current"
      active_power:
        name: "T-Series PV3 Power"
    pv4:
      voltage:
        name: "T-Series PV4 Voltage"
      current:
        name: "T-Series PV4 Current"
      active_power:
        name: "T-Series PV4 Power"

    total_energy_production:
      name: "T-Series Generation Total"
    energy_production_day:
      name: "T-Series Today Yield"

    generation_power:
      name: "T-Series Generation Power"
    grid_power:
      name: "T-Series Grid Power"
    loads_power:
      name: "T-Series loads Power"

    inverter_temp:
      name: "T-Series Inverter Temperature"
    ambient_temp:
      name: "T-Series Ambient Temperature"
    boost_temp:
      name: "T-Series Boost Temperature"

    inverter_status:
      name: "T-Series Inverter State"
      internal: true
      on_value:
        then:
          - lambda: |-
              if (x==0) {
                id(inverter_mode_text_sensor).publish_state("Offline");
              } else if (x==1) {
                id(inverter_mode_text_sensor).publish_state("Online");
              } else if (x==2) {
                id(inverter_mode_text_sensor).publish_state("Error");
              } else {
                id(inverter_mode_text_sensor).publish_state("Waiting for response...");
              }

# Uncomment this sensor and the i2c section to use the AHT10
#  - platform: aht10
#    temperature:
#      name: "Foxess inverter ambient Temperature"
#    humidity:
#      name: "Foxess inverter ambient Humidity"

#i2c:

```

**Comment by spitfire** [comment]
> You have to replace everything below the 'uart:' section with the sections from the new yaml example.
> 
> If you're worried about entities changing name in Home Asisstant, you have to make sure the new sensor has the same 'name' field in the yaml file. 

thanks for adapting it for me, that helped me a lot!

I've adapted it further to work with LilyGo T-CAN485 board I'm using (works great with no need to add voltage controllers or RS485 components):

```
# Set pins required for LilyGo T-CAN485 board
output:
  - platform: gpio
    id: ENABLE_PIN # Enable the chip
    pin:
      number: GPIO19
      inverted: true
  - platform: gpio
    id: SE_PIN # Enable autodirection
    pin:
      number: GPIO17
      inverted: true
      allow_other_uses: true
  - platform: gpio
    id: ENABLE_5V_PIN # Enable 5V pin for RS485 chip
    pin:
      number: GPIO16
      inverted: true

# Configure uart that will be used
uart:
  id: uart_bus
  rx_pin: GPIO21
  tx_pin: GPIO22
  baud_rate: 9600
  # debug:
```

I have an optional light section for control over the built in LED:

```
light:
  - platform: esp32_rmt_led_strip
    id: led_light
    name: "${friendly_name} Light"
    pin:
      number: GPIO04
    num_leds: 1
    rmt_channel: 0
    rgb_order: GRB
    chipset: ws2812
```

which I'm using to show different color depending on energy production:

```
generation_power:
    name: "T-Series Generation Power"
    on_value_range:
    - below: 1.0
      then:
        - light.turn_on:
            id: led_light
            red: "100%"
            green: 0
            blue: 0
    - above: 1.0
      below: 1000.0
      then:
        - light.turn_on:
            id: led_light
            red: "100%"
            green: "100%"
            blue: 0
    - above: 1000.0
      below: 2000.0
      then:
        - light.turn_on:
            id: led_light
            red: 0
            green: 0
            blue: "100%"
    - above: 2000.0
      then:
        - light.turn_on:
            id: led_light
            red: 0
            green: "100%"
            blue: 0
```

I had to add configuration for flow control pin, it seems to be GPIO17 on that board:

```
flow_control_pin:
    number: GPIO17
    inverted: true
    allow_other_uses: true
```
